### ISSUE TITLE
How should I interpret the PLMSearch similarity value

### ISSUE THREAD

**Issue by Rohit-Satyam** [maovshao/PLMAlign#2]
Hi @maovshao 

I was using PLMSearch database to find remote homolog of some of my proteins and I was wondering how do I explain similarity value of 0.995 against the target that I got. I am aware that the sequence similarity will be less than 25% but this 99.5% similarity says what exact? Does it say that the query protein when folded will have 99.5% of the fold similar to the target identified by PLMSearch (structure-wise)? Kindly help.

**Comment by maovshao** [comment]
If you want to learn more about PLMSearch's similarity, you can refer to the "Method --- Similarity prediction" section of the [PLMSearch paper](https://www.nature.com/articles/s41467-024-46808-5).

In short, the similarity provided by PLMSearch is a "structural similarity predicted by a deep learning model with sequences as input". Its relationship with the actual structural similarity can be seen in "Fig. 6: Reference similarity" and "Supplementary Table 12" of [PLMSearch paper](https://www.nature.com/articles/s41467-024-46808-5). 

In this case, since 0.995>>0.7, it means that PLMSearch's similarity prediction model (SS-predictor) believes that the two proteins are structurally similar (or more strictly speaking, belong to the same fold).In addition, I think the "PLMAlign score" can more accurately reflect the similarity between the two protein structures. It is a more refined similarity calculated by PLMAlign. 

The above mentioned are all structural similarities predicted by sequences. If you are interested in the actual structural similarity, please prepare your real/predicted structures and use TM-align to calculate.

Hope the above answer is helpful to you.

Best.

**Comment by Rohit-Satyam** [comment]
I have two plasmodium proteins: `O77324`, `Q8I341` (AF structure present) for which PLMSearch gives me `~0.9958` similarity and remote homology for `Q8I3Z1` (AF structure absent). Now `Q8I3Z1` is a 10K amino acid long and is without structure. So I am not sure how PLMSearch can say that that the proteins `O77324`, `Q8I341` will have a same fold as `Q8I3Z1`!! Just thinking

Also if `O77324`, `Q8I341` are predicted to have same fold as  `Q8I3Z1` they must also have same fold when aligned together right? But there TMalign score is also not good see [here](https://www.rcsb.org/alignment?request-body=eJylj81uwkAMhN%2FF5%2FyIJhIoNy5IPSHOFYrMxiEr9ifd9bagKO%2BOF56g6s3yjOcbL%2FCdKDygW8DPrL2LeQzEKbg%2BkohOUT8gI3QcEq0FKO%2BY7px91g8EHcyow6%2BOBAVY4skPWXNos8a2RKOvDuQySoKSZBLI1wIpGDFMzHPs6hrNPOHozVDRRVeoqnSrR20o1vtDedxum4%2B2PGzKjDT9T1spPQpv9MGidAFr34tIhlR%2BJHfA%2BLC9ljqwh3Ut%2FoQ87T6bdvNP5Fmo8IqUj8%2FrE9UFfDg%3D&response-body=eJzlWdtu2zoW%2FRc%2Fx6nul7wJEmURpHgkkVBBFEXgJk5rTOJ0YvvMFEX%2B%2FSw6bSoxc2y553EcNLFErs29N%2Fdlkf0%2BW2%2FuHmdX32f7%2Ffp2djVLnDBc%2Bs7d%2FM6P3HngJKt58il05qGbxHGapDeJ484uZtvdcrffYn7%2BR91wosjs%2BWL2sNotjajl%2Ffrz5mG12V0%2FPN6uMOnrcv30n%2FV2BeBgbLX78miW3D3MD2%2BNiKfVdn%2B%2Fg%2BAP37HG0%2F5mt8erw%2BP%2B6R6Tv%2Bx2X7dX794t779%2BWd493t9erj6tL5c3l%2Ft%2Fvbtb36%2B277Jy%2Fkcc%2B14wL925UeD%2B%2Bs%2Fg8mZ9h9XvHp8eljuIeXh4ebHeXn9ab5ZP32ZXd8v77epitlk%2BGJWHUoy9q%2FvVzW79uDnYt%2F32cH3wVjZ7fr44S7U2oX7g%2FlPVXqUcV%2B3jxS8nXr96%2FuDNp9VnQIxnP4xRF7NPq8%2FX29W%2FDy%2B84OV5vbld%2FXd2Fbrpxex%2Btfm8%2BzK78o3pfw%2F1ozHUd39B3ePQIBxDk2DyqkFqQZNf0Pg4NEzG0DSerHDkj6BREP2CeiegkQVNJyscjzcniqZ7OLZWjcJf0OA4NHHH0NibrHBquSmNJivsOmNj48A%2FAxtZ2OnWev5Y5ySengGeH4%2BxiT993cBaN0kn2%2BslY2wajvLn48XRlA9SK4XOyPnQGVt8TtKHkfPbWR9GVp06J%2B1NAP9u3ntWMpyT%2BFZtHWX%2BCXsjb1yrotCfvq7vWdj4DKxdN6bvbxQ4FnZ6FkbBOK7OKTpRbO3RGVUndu3KMb3qxG5iYafbGx%2BrOie7wtjecypHnIz3yK4cIBS7p%2BVm%2B0JWfhII98L58fM%2Fv6HeOJdO6AeB7zghBi7TyPNQKkI%2FwYMXRQliMEQ4OBdz59IN3cgPXcc1D16IcE0894AKA%2BRb7KEuOOYxidLUwb%2FYTHRSN0gC84gh1%2Fc813MCxzci%2FfDSjZ3Q8Zw0iS%2Fc9NL1IpBZJ0bRmEeXcQqW54dRmkBVw5j2Dw8H1gUGevP4k33%2Bubzfg3xhIUTi7ttXQ8Tgtf1qc7Oar29Bq9a7bzPj3deZpjb8mKnq%2BUHWcAJWDl8ndLUsZoavbcDTNtdYdX27X10b4rw1ZdQMHAjj6vbnoNHLR4dx3Sg0amMLDRS7hW32TfE0jzePf66elp%2BxxgfEcvjxhRT%2BUNzihD9fQ5%2BaEd5LWXIhuGzxjXCZ50wwVlZ9IXrJ8wUlRc8r0RWdlJwWjDAqFK8J10wQQTWRmhBdYERjiAkhKGeiXiwE46LPRZbzMsdbIVtR1QLCIRdAIXpa8KIglNNMlE0pJO%2BKngiutBKSVApaMaKlhlBpppZF2%2BJ7y8wiEi9lxbUgtGdkAQ1EUchGlAUppGxLVsoeAoxCtBKKFYQrIbSgeAPJbQFtBS1a2FMVlMLauheyL3QrirpQACpmPqLNtBSlzpgseCMlMGQhc7bIWSYLBZeVWCmTi5o1QswuBpT7KFkZJWAwLFbBKdpsNTI%2FmZz4FtsIk0F9ddNTzcjqY8H0nnCEN0cnoOlvd0C7IZzRAGNLYcNZJvbsf0K5rc4ZD7ruic1JLDcl7mRbU7tvetOhR4j%2BKWhoQad3r9Rq1s4Ztlq92kkmb47rjOP%2F0H9fNXZOgF0LHA5z9lTCe6FF9J3p4YjOOsZ6gyzwwxNgKzbSIR9zT10MWEc51w%2BHagemQ31efn0plIN5g0koi2aNUbGzWftocBBEgW%2BNRsM4eTs6pG224Cj0jg2GVvyNBu24HtUGu5iNBtMjg4lzROzw%2FJnag2lwRGxqt5JRshxZM3YGa4b2oDssKbZGcTjYl9gaTN7UhVEeDP0X2KORZyfocDQZ7Jofhc8fzYQhNZJ5zxmjCmQFbCXPtVoQArJCwBhAC7Ku4LwnkuERfIkS0JKWN7wjjDdKl2A7IAsSVAjsocBYmRO5UExzyjSjWnBDZUrd9kVfVZnsZSM55oE0SQVmQjsjt1XiwEJ4w2hj1mVFyamgmRJlh%2FEGmoBMyZdZTIA5tW2GWUwaIgaSBR0M1zr8ffkxH334iAMbYz%2FemQ9%2FeSFYJzq2gEAKqVRT6CK5ghZKdDoXmhnOB9InC8JqAm10QZTO8ZtARCGZUhQPi14aGVrkRS8qWhYCVFCXIu9hKZE1KJvKYAAFI5OGrKkWXIwWQhAGVmooWte20L%2FXqlXGStm957lUGbheJYjmimASo4UE%2FzO4vmIF%2BBqtwDIVeKXxAoRrMLqilFIr1Ta05aUoWiKE0kW9ANfrjbES6xHVMSpFxktSa6lELxiIIYTUYvHqJCKgPs%2Fhp5aTrFHYuFIpTUULnXQlQSZhdM97w1YRCFCP6IOraNllLQOLrnrG4NUSIK3xVYBX9z1CB7S6InWV15XxvTZbx1mPnawrsPSyrDjoqVYUf7TSCLO%2BMLyVKknwC04kAr%2BpqGQBaA0Si6dK6qwBt18sYLiUlOUahJpIOF2yGk5sFP9hHlyNjSAZQp4YZ8pC8J9mF8Wih%2BlycYgnKKewCwW0JAgE2Ruzqa7aFv7PRc3hMaYQrC2DPk0hZIaYgoZdVfeM0pZpyboSR42OSYZsIYv3lBF4QvOCy6qDOGwolX1FuwwZoEkvOsolbCcKB5VevM%2BakiuJeIejuewymVGqWuyjbihdmBDjtc75AjHGEZmLnFKO803WNKTEzlJeaiLq3BxpqGDlguB0gNMEbajRSmlsiipLeJo3pOkbxouu7bJM8LzkXDcIDISN6rFrJa9KIkjJtAK4NjCkDo4mosYSECvzDlEIFA4MHMDMbP57nH8QJJ2uEX8mbcw4ha4IZ9IQRDjhJpl%2B81jxtpUeuw%2B07vTc2CrLx%2B4DrXs5b9BHopMXc2Olw9HFjXvqqsq6BI3dodHJKZpv3aHEsdXFjmHHxOqcW9%2FYuiNLhveYp84X9o1xesaJyPofl2R07DyFTS0SOmzqp5xl%2FR9GGky%2FfI3j0MIOidEpb1mMPx2eeP0o%2BTsSOjqQe2%2BIphdYfhvF7xEmOTpx2PRrfCpwbaKUJEdYaJIcIcZJah%2BRRoNH9B0dNWzk6CzhvWFYwREyOT5J2NC3R4Xn%2F4cbu%2Be%2FAM1Pyr4%3D&encoded=true).

**Comment by maovshao** [comment]
Hi, thank you for sharing. We also tested the protein pair `O77324-Q8I341`.

Basically consistent with your findings, the structure of this protein pair is not similar (`TM-score < 0.2)`, but the similarity of PLMSearch is as high as `0.9952`. This is mainly because when PLMSearch finds that the COS Similarity between two protein embeddings is particularly high (`> 0.995`), PLMSearch will directly use the `COS Similarity` as the `Similarity` (Explained in the "Method --- Similarity prediction" section of the [PLMSearch paper](https://www.nature.com/articles/s41467-024-46808-5)). This means that the pre-trained model we used (`ESM-1b`) believes that this protein pair is similar. But as you can see, the `COS Similarity` between the embeddings generated by the pre-trained model `ESM-1b` is not always correct.

PLMSearch has many ways to avoid such `Wrong Pairs`, but the `O77324-Q8I341` protein pair has the following special features:

1. Neither `O77324` nor `Q8I341` can scan any `Pfam Domain`, which means that the `PfamClan` module in PLMSearch will not work in this pair.
2. The COS Similarity between them is only slightly higher than the threshold (`0.995`).
3. The length difference between the two proteins is large (`337/1165`, nearly 3 times). For running speed and space considerations, PLMSearch uses the protein embedding obtained by averaging the amino acid embeddings, and the length information will be lost in the process (Explained in the "Discussion" section of the [PLMSearch paper](https://www.nature.com/articles/s41467-024-46808-5)).

In general, the `O77324-Q8I341` protein pair is hard to predict. We are conducting further research and will refer to this case. Our new method will do better in these hard cases.

Best.
